name: CI/CD For Production Environment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Pull code and run container
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' # we tell Github to only execute this step if we're on our master branch (so we don't put unfinished branches in production)
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master # An action made to control Linux servers
        with: # We set all our secrets here for the action, these won't be shown in the action logs
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          port: 22
          script: |
            rm -rf Kyoto-Website
            git clone https://${{ secrets.GIT_KEY }}@github.com/anhocva214/Kyoto-Website Kyoto-Website
            cd Kyoto-Website
            git checkout develop
            cp ../env/kyoto-website-dev.env.development ./.env
            bash run.development.sh